POST http://localhost:5200/api/booking/flight
content-type: application/json

 {
        "leavingAt": "1975-08-19T23:15:30.000Z",
        "returningAt": "1975-08-19T23:15:30.000Z",
        "country": "nigeria",
        "state": "rivers",
        "destination": "lagos",
        "tripType": "round",
        "passangerSize": 1,
        "promoCode": "n/a",
        "amount": 40000,
        "email": "arms@gmail.com",
        "user_id": "611f72a10ef184001615d028",
        "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoiNjExZjcyYTEwZWYxODQwMDE2MTVkMDI4IiwiZW1haWwiOiJjcnlzYW5jdHVzMjRAZ21haWwuY29tIn0sImlhdCI6MTYyOTQ1MDkxMywiZXhwIjoxNjMwMDU1NzEzfQ.SfVXmNp-W0HrxWrIIxB6asY7i77IY_P4cCiBgkpOZoo"
}