version: '3.8'
services:
  postgres:
    image: postgres:14.1
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=company_db
    ports:
      - '5432:5432'
    expose:
      - 5432
volumes:
  postgres:
